### ISSUE TITLE
Issue with adding the plugin

### ISSUE THREAD

**Issue by mrcspyhooma** [myluna08/homebridge-rituals#1]
Every time I try to install the plugin and edit the config.json, homebridge giving me this error: 

![Screenshot 2020-02-17 at 17 57 42](https://user-images.githubusercontent.com/61158830/74674016-bae6c000-51b0-11ea-9ecb-92e947fd6c12.png)

**Comment by myluna08** [comment]
Did you use the homebridge UI to install the plugin ? if you use homebridge UI please check that you install plugins using SUDO https://github.com/oznu/homebridge-config-ui-x#configuration, i assume you are running homebridge on raspberry pi with this UI-X module to manage homebridge.

**Comment by mrcspyhooma** [comment]
I added the "sudo:true" to the config file and reinstalled the plugin again, but it stil gives me the same error. I am sorry

As you can see, the plugin is successfully installed:

![Screenshot 2020-02-17 at 18 51 06](https://user-images.githubusercontent.com/61158830/74676533-79591380-51b6-11ea-8c89-dc09bba349d4.png)

**Comment by myluna08** [comment]
Assume you have entered the correct configuration on config.json, did you restart your homebridge after enter the config? 

`"accessories": [ { "accessory": "Rituals", "name": "My Genie", "account": "xxx@xxx.com", "password": "yyyyyyy" } ]`

**Comment by mrcspyhooma** [comment]
Yes I did all of this!

**Comment by myluna08** [comment]
Let me check in a new environment.

**Comment by myluna08** [comment]
Can you check that inside your installation if there are a file inside your Homebridge??

/usr/lib/node_modules/homebridge/lib > check if user.js exists!!

I think there is an issue with a const inside my code
const user = require('../homebridge/lib/user').User;

**Comment by mrcspyhooma** [comment]
No there is no user.js file!

**Comment by myluna08** [comment]
ah! that's the problem, I use this file I supposed was inside homebridge to check about your storage, that's to locate were the plugin can write a file to storage the local information.

**Comment by myluna08** [comment]
I upgrade a new version with FAN control included but this does not correct your bug, this night I will include some function inside the plugin to be native functions in order to solve your bug

**Comment by myluna08** [comment]
Dear @mrcspyhooma, I upload a new 1.0.8 version with this bug solved, please try again!!

**Comment by mrcspyhooma** [comment]
All right I will try it!

**Comment by mrcspyhooma** [comment]
Issue is fixed by update!

**Comment by mrcspyhooma** [comment]
Issue is fixed by update!
