### ISSUE TITLE
When HB Starts 

### ISSUE THREAD

**Issue by Christian-CFP** [myluna08/homebridge-rituals#10]
Hi its me again 😁
So there is an issue related to Homebridge when it starts/boot up. 

The Genies shows off but only the state (on/off). With this state HomeKit does not recognize them and shows as not connected. 

If you then turn the fan speed in hk (33, 67, 100%) it works great and HomeKit shows them as working normal. 

So can you set it right from the start with fan speed selected?

**Comment by myluna08** [comment]
I still haven't found a solution, I'll keep looking

**Comment by myluna08** [comment]
@Christian-CFP what about this issue using 1.1.14 ?

**Comment by Christian-CFP** [comment]
Works great.

**Comment by myluna08** [comment]
@Christian-CFP Nice to hear this. Enjoy your genie.
