### ISSUE TITLE
@myluna08 I have installed homebridge-rituals@1.1.10 but is seems that the 'bug' is back. I can see the status in the Home app. But switching the Genie on or off in the Home App is not working.

### ISSUE THREAD

**Issue by myluna08** [myluna08/homebridge-rituals#14]
@myluna08 I have installed homebridge-rituals@1.1.10 but is seems that the 'bug' is back. I can see the status in the Home app. But switching the Genie on or off in the Home App is not working.

_Originally posted by @tomsteenbakkers in https://github.com/myluna08/homebridge-rituals/issues/7#issuecomment-717867249_

**Comment by myluna08** [comment]
@tomsteenbakkers can u report your log in hb ??
I've installed 1.1.10 (of course) and works fine for me, it's true that the first time I open home app, genie is shows as an unresponsive accessory (I working on that) but genie as accessory works fine when I tap to ON and OFF. Explain me what's happened in your environment.

**Comment by tomsteenbakkers** [comment]
I have installed 1.10, enabled debug and this is the debug log. Switching on or off is not working.

![image](https://user-images.githubusercontent.com/24613800/97627471-b525c780-1a2b-11eb-92b4-405210e00337.jpeg)

![image](https://user-images.githubusercontent.com/24613800/97627482-b951e500-1a2b-11eb-9bba-a2588434708d.jpeg)

If I downgrade to 1.8 everything is working perfect.

**Comment by myluna08** [comment]
I can't reproduce it, works fine for me switching On and Off, from Rituals App, from Homebridge and from Home App, can you send me more tests ??

**Comment by myluna08** [comment]
@tomsteenbakkers try with 1.1.12

**Comment by tomsteenbakkers** [comment]
Tried 1.13 but no luck. Only 1.8 is working

If I revert to 1.8 it’s working again.

Will try to do some more tests.

Tom

On 2 Nov 2020, at 10:30, Victor Montes <notifications@github.com> wrote:

﻿

@tomsteenbakkers<https://github.com/tomsteenbakkers> try with 1.1.12

**Comment by Vanhouttethomas** [comment]
Hi!
I seem to be having a similar issue.

Setup:
Genie 2.0 connected with Wi-Fi (firmware 5.0)
Using official fragrance
iOS 14.2 (iPhone 11 Pro)
Home Hub: yes (AppleTV 4K)
homebridge-rituals v1.1.13
Homebridge Up To Date v1.1.6 (Raspberry Pi 4B)

Issue:
Status is ‘on’ by default with ‘no response’. (But the Genie is off in reality)
I disable and enable the accessory and then the Genie is working .. (no longer ‘no response’)

**Comment by gloaguen** [comment]
I have installed this plugin new with version 1.1.13
I can turn ON the fan, but I can't turn OFF the fan.

Also my Genie is recognised as version 1.0, but it's a version 2.0

Please let me know what debug info you need for fixing this.

**Comment by myluna08** [comment]
Update to 1.1.14 @gloaguen @tomsteenbakkers

**Comment by tomsteenbakkers** [comment]
Plug-in is working!  It’s also must faster as the previous version.

Excellent job.
