### ISSUE TITLE
Genieis always on in homekit

### ISSUE THREAD

**Issue by dongilles** [myluna08/homebridge-rituals#16]
Hello,

I have tried your plugin (first one I tried so very little experience) but in homekit the genie is always on for some reason.
I can turn the genie on and off through the app so that works perfectly.

Is there anything I can do to change this?

**Comment by neffets73** [comment]
Hi, I just wanted to add that I am experiencing the exact same symptoms as described; always-on status in Home app.

**Comment by gloaguen** [comment]
I have installed this plugin new with version 1.1.13
I can turn ON the fan, but I can't turn OFF the fan.

Also my Genie is recognised as version 1.0, but it's a version 2.0

Please let me know what debug info you need for fixing this.

**Comment by myluna08** [comment]
Preparing new version with this issue solved (always on) for this weekend.
about the version, that value are based on a firmware. There are not a table in Rituals with exact pairing between fimware and version model.

Please put here your start in homebridge with debug mode enabled.
`start Homebridge with -D.`

**Comment by myluna08** [comment]
New version 1.1.14 published

**Comment by marked80** [comment]
Hi! The always on issue is fixed indeed! The version shows 1.0 while I have the 2.0. My firmware version is 5.0 according to the rituals app. I also cannot see the installed fragrance in HomeKit, however it is available in Homebridge.

**Comment by myluna08** [comment]
@marked80. Nice to hear this. Enjoy your genie. if you like my work:https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=4YXRZVGSVNAEE&item_name=Just+for+a+coffe&currency_code=EUR&source=url

**Comment by marked80** [comment]
> @marked80. Nice to hear this. Enjoy your genie. if you like my work:https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=4YXRZVGSVNAEE&item_name=Just+for+a+coffe&currency_code=EUR&source=url

Just donated!
