### ISSUE TITLE
Genie shown as "not responding" in HomeKit but actually working

### ISSUE THREAD

**Issue by bondskin** [myluna08/homebridge-rituals#17]
All,

I am running two Genie (model 1) devices at home. 
Controlling them via the plugin is working as expected, however both appear in the Home app as "not responding" in the upper status section.
I can manually stop/start them using the Home app or Siri, despite this error Homekit message.

Is this a timeout issue?
Any chance to get rid of this ?

(See screenshot, "Keine Antwort" = "not responding")
![IMG_9172](https://user-images.githubusercontent.com/55050117/103522100-30678780-4e7a-11eb-9bd2-30850c53ae90.jpg)

**Comment by myluna08** [comment]
preparing new version for this weekend with this issue solved

**Comment by bondskin** [comment]
Hi @myluna08 , I just installed an update (1.1.14) which fixed the "not responding" message for the first of my two Genies. Actually, the first device mentioned in the JSON file is fixed. The second device is still reported as "not responding" although fully functional via Home app.
Does this make sense?
Mike

**Comment by bondskin** [comment]
After one day both Genies were working as expected. Thanks

**Comment by myluna08** [comment]
@bondskin. Nice to hear this. Enjoy your genie. If you like my work: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=4YXRZVGSVNAEE&item_name=Just+for+a+coffe&currency_code=EUR&source=url
