### ISSUE TITLE
When putting speed at 100%, it will turn off

### ISSUE THREAD

**Issue by mrcspyhooma** [myluna08/homebridge-rituals#2]
When you put the genie at 100% fan speed, the genie will not put any air through the parfum. The maximum speed is 75%

**Comment by myluna08** [comment]
I will check and repair in the next release!

Enviado desde mi iPhone

**Comment by myluna08** [comment]
Search a line and put it here your results, in your homebridge log like the following line when you put your accessory to 100%?

`** setFanSpeed setting Fan Rotator at xxxxx`

**Comment by mrcspyhooma** [comment]
![Screenshot 2020-02-21 at 14 49 58](https://user-images.githubusercontent.com/61158830/75039691-79f4f100-54b9-11ea-9a97-6f891a77f2c9.png)

**Comment by myluna08** [comment]
OK I see the problem, today you will have a new version 1.0.9 with the bug solved.

**Comment by myluna08** [comment]
Upgraded, new version available!
