### ISSUE TITLE
Fragrance not showing in Homekit

### ISSUE THREAD

**Issue by marked80** [myluna08/homebridge-rituals#22]
I cannot see the installed fragrance in HomeKit, however it is available in Homebridge.

**Comment by myluna08** [comment]
Dear @marked80 , that's ok because not all properties in homebrige can be exported and published to HomeKit. Maybe in the future will be supported.

**Comment by myluna08** [comment]
Enjoy your genie. If you like my work: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=4YXRZVGSVNAEE&item_name=Just+for+a+coffe&currency_code=EUR&source=url

**Comment by marked80** [comment]
Thanks! I already thought something like that. Keep up the great work
