### ISSUE TITLE
characteristic value expected float and received undefined

### ISSUE THREAD

**Issue by Christian-CFP** [myluna08/homebridge-rituals#28]
Since Homebridge 1.3.1:

2.3.2021, 06:27:53 [HOOBS-Server 6A21@Genie 1@Genie 1@Rotation Speed] characteristic value expected float and received undefined
2.3.2021, 06:27:53 [HOOBS-Server 6A21@Genie 1@Genie 1@Rotation Speed] characteristic was supplied illegal value: number 0 exceeded minimum of 1
2.3.2021, 06:27:53 [HOOBS-Server 6A21@Genie 2@Genie 2@Rotation Speed] characteristic value expected float and received undefined
2.3.2021, 06:27:53 [HOOBS-Server 6A21@Genie 2@Genie 2@Rotation Speed] characteristic was supplied illegal value: number 0 exceeded minimum of 1
2.3.2021, 06:27:53 [HOOBS-Server 6A21@Genie 3@Genie 3@Rotation Speed] characteristic value expected float and received undefined
2.3.2021, 06:27:53 [HOOBS-Server 6A21@Genie 3@Genie 3@Rotation Speed] characteristic was supplied illegal value: number 0 exceeded minimum of 1

**Comment by bondskin** [comment]
same here
[21/03/2021, 10:43:34] [homebridge-rituals] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

**Comment by Christian-CFP** [comment]
I see, you do not carry any more! Shame...
