### ISSUE TITLE
Have you stop development?

### ISSUE THREAD

**Issue by Christian-CFP** [myluna08/homebridge-rituals#3]
Hi Victor, have you stop development?

**Comment by myluna08** [comment]
Have you got any code problem?

**Comment by Christian-CFP** [comment]
The feature I am looking for is to control more than one. I've got 3 on one account and I can only control all at the same time.

In addition, the log is quite filled with status messages from the genie. Every some seconds (Ok, every 2 min.).

`3.5.2020, 11:51:54 [Genie] getCurrentState of genie
3.5.2020, 11:51:55 [Genie] hubs 200 OK!
3.5.2020, 11:51:55 [Genie] currentState of Genie => false`

And in addition there are new Genies without battery inside.

So maybe I can help testing?

**Comment by myluna08** [comment]
Dear friend,

The best way to do that is implementing a new module using platforms not accessories.
While Accessory is an individual object, a Platform is a group of objects.

Unfortunately I haven't more Genies in my house, so I can't see in clear what contains and can't identify what happens with more than one.

There are an alternative to this simple way, I can try identify each accessory.
My idea is that you can replicate your declaration inside your config.json using two or more using the specific hub-identify. The way to identify is just including in the general LOG the hub-id's, and if you don't specify anything in your config.json, It will work as now, but adding a tag with hub-id it will control only one, then you just need to replicate your section using the next hub-id and so on.

If you feel confortable with this alternative, i will work in this way during the following week.

**Comment by Christian-CFP** [comment]
Sounds great. And if ready please send also a sample code.

**Comment by myluna08** [comment]
> Sounds great. And if ready please send also a sample code.

I will notify you when I have updates.

**Comment by Christian-CFP** [comment]
Hey Victor, some news regarding this topic?

**Comment by Christian-CFP** [comment]
Some news?

**Comment by Christian-CFP** [comment]
Nothing?

**Comment by myluna08** [comment]
Hi, I recently acquired new genie more. Waiting to receive I will start code task during the following week

**Comment by myluna08** [comment]
Now you can update a new 1.1.0 version, now you can control more than one genie. Just need to replicate the config.json, see the README for details. Enjoy.
