### ISSUE TITLE
The log operation...

### ISSUE THREAD

**Issue by Christian-CFP** [myluna08/homebridge-rituals#6]
This is not a bug but maybe you can solve this.
I have 3 Genies. In the log if I control one of them:

[Genie 1] set Genie 2... or set Genie 3 or Genie 1

It would be better if there was a general name for your plugin like only "Genie" or "Rituals"
[Genie 1] is the last Genie in the config that will show up here. So if in the config is "Genie Wohnzimmer" than:
[Genie Wohnzimmer] set Genie xyz to false

Ideal is something like:
[Rituals] set Genie Wohnzimmer to true... or
[Genie] set Genie Wohnzimmer to true...

**Comment by myluna08** [comment]
In log should be appear what genie action was executing but this was an issue due to an accessory persistance memory. But should work ok.

**Comment by Christian-CFP** [comment]
e.g. This is a entry:

8.7.2020, 11:49:51 [Genie Wohnzimmer] Genie Zoe: Set ActiveState to => true

Ist should be:

8.7.2020, 11:49:51 [Rituals or Genie] Genie Zoe: Set ActiveState to => true

**Comment by myluna08** [comment]
done! available in 1.1.5
