### ISSUE TITLE
1.1.6 only info no control in HomeKit app

### ISSUE THREAD

**Issue by PaulBartelings** [myluna08/homebridge-rituals#7]
Hi there, I have only status but no control in my HomeKit app. So if I turn geni on it is not responding. If I turn geni on with geni app status in HomeKit is changed.

**Comment by myluna08** [comment]
Insufficient information, please provide more detail. Number of genies, a copy of log when you execute actions in homekit, a copy of your configure.json.
Remember obfuscating accounts and credentials.

**Comment by szunny** [comment]
same here:
I have a Genie 1.0, Firmware 1.2.9.
homebridge is running on macOS 10.12.6. 
Unfortunately I have no communication transcript.
the log:
[2020-7-20 16:37:49] [Wohnzimmer] RitualsAccesory -> init :: setActiveState: function(active, callback)
[2020-7-20 16:37:49] [Wohnzimmer] RitualsAccesory ->  setActiveState to true
[2020-7-20 16:37:49] [Wohnzimmer] Wohnzimmer :: Set ActiveState to => true
[2020-7-20 16:37:49] [Wohnzimmer] RitualsAccesory -> finish :: setActiveState: function(active, callback)
[2020-7-20 16:37:49] [Wohnzimmer] RitualsAccesory -> ajax :: setActiveState :: api/hub/update/attr/ OK :: 200
[2020-7-20 16:37:49] [Wohnzimmer] RitualsAccesory -> ajax :: setActiveState :: api/hub/update/attr/ BODY :: undefined

How can I help debug the problem further?

**Comment by myluna08** [comment]
Dear all, sorry for the delay of answer. How many genies have in your account ?

**Comment by tomsteenbakkers** [comment]
I have the same issues. In the log during startup the following line appears:

```
[8/20/2020, 7:56:45 PM] [Rituals Genie] Initializing Rituals accessory...
```

When using the fan control in HomeKit the following items appear in the log:

```
[8/20/2020, 8:06:41 PM] [Rituals Genie] Livingroom :: Set ActiveState to => false
```

I have only 1 Genie version 2.

I notice also that the fan speed is in the Eve app max 3%. In the Home app you can set it to 100%

![image](https://user-images.githubusercontent.com/24613800/90819455-4bed4e00-e330-11ea-9c80-b0b878d575e0.jpeg)

**Comment by myluna08** [comment]
Log issues are not a bug, completely normal.
Fan speed in genie are from 1 to 3, your app are using this values are % but wrong. In HomeKit works ok and in Rituals Apps fan speed is assigned ok.

`  this.service
  	.getCharacteristic(Characteristic.RotationSpeed)
  	.setProps({
        minValue: 1,
        maxValue: 3
      })`

**Comment by tomsteenbakkers** [comment]
Ok, but still the plugin is not working. I see in the log that the ActiveState is set to false or true, but nothing happens on the Genie. When using the native Rituals app I can control the Genie and the status is reflected in the Home app, but controlling the Genie from the Home app is still not working. Is there a way to increase the log level so I can see what might go wrong.

**Comment by szunny** [comment]
unfortunately, the original issue remains. Genie does not react to "Set ActiveState" commands. Is there any way I can help to debug the problem?

**Comment by szunny** [comment]
> Ok, but still the plugin is not working. I see in the log that the ActiveState is set to false or true, but nothing happens on the Genie. When using the native Rituals app I can control the Genie and the status is reflected in the Home app, but controlling the Genie from the Home app is still not working. Is there a way to increase the log level so I can see what might go wrong.

+1

**Comment by tomsteenbakkers** [comment]
Is there a way how I can support you in fixing this bug? It's a really nice plugin but now I can not use it with the HomeKit automation (i.e. door open -> Genie off).

**Comment by myluna08** [comment]
Dear Tom,

Just for understand, @szunny @tomsteenbakkers your problem are when you tap con the box in HomeKit to enable genie, your genie does not start, but works with rituals app. right?

Start your homebridge with -D option to enable debug.
Then paste here your log from start until you set the activeState value.
Describe your platform, homebrige version, raspberry version & settings...

**Comment by myluna08** [comment]
> Is there a way how I can support you in fixing this bug? It's a really nice plugin but now I can not use it with the HomeKit automation (i.e. door open -> Genie off).

In response to your automation, I created this on my own platform and works fine.

**Comment by tomsteenbakkers** [comment]
> Dear Tom,
> 
> Just for understand, @szunny @tomsteenbakkers your problem are when you tap con the box in HomeKit to enable genie, your genie does not start, but works with rituals app. right?

Yes, the Rituals app works, but switch on and off from HomeKit not. I do see the Genie and it also show the status, but I can not switch it on or off

> 
> Start your homebridge with -D option to enable debug.
> Then paste here your log from start until you set the activeState value.
> Describe your platform, homebrige version, raspberry version & settings...

Here are the specs of my HomeBridge:

- Running on a RaspberryPi 4 with 4 GB and Ethernet and Raspbian GNU/Linux Buster (10)
- Installed Homebridge using Homebridge Config UI X
- Node.js Version = v12.18.3
- Npm Version = v6.14.8

Here is the log when pressing the accessory to On
```
[8/26/2020, 1:35:58 PM] [Genie] RitualsAccesory -> init :: setActiveState: function(active, callback)
[8/26/2020, 1:35:58 PM] [Genie] RitualsAccesory ->  setActiveState to true
[8/26/2020, 1:35:58 PM] [Genie] Genie :: Set ActiveState to => true
[8/26/2020, 1:35:58 PM] [Genie] RitualsAccesory -> finish :: setActiveState: function(active, callback)
[8/26/2020, 1:35:58 PM] [Genie] RitualsAccesory -> ajax :: setActiveState :: api/hub/update/attr/ OK :: 200
[8/26/2020, 1:35:58 PM] [Genie] RitualsAccesory -> ajax :: setActiveState :: api/hub/update/attr/ BODY :: undefined
```

Here is the log when pressing the accessory to Off

```
[8/26/2020, 1:37:17 PM] [Genie] RitualsAccesory -> init :: setActiveState: function(active, callback)
[8/26/2020, 1:37:17 PM] [Genie] RitualsAccesory ->  setActiveState to false
[8/26/2020, 1:37:17 PM] [Genie] Genie :: Set ActiveState to => false
[8/26/2020, 1:37:17 PM] [Genie] RitualsAccesory -> finish :: setActiveState: function(active, callback)
[8/26/2020, 1:37:17 PM] [Genie] RitualsAccesory -> ajax :: setActiveState :: api/hub/update/attr/ OK :: 200
[8/26/2020, 1:37:17 PM] [Genie] RitualsAccesory -> ajax :: setActiveState :: api/hub/update/attr/ BODY :: undefined
```

**Comment by myluna08** [comment]
Plase put here your config (obfuscating account and password)

**Comment by tomsteenbakkers** [comment]
> Plase put here your config (obfuscating account and password)

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxx",
        "port": xxx,
        "pin": "xxx"
    },
    "accessories": [
        {
            "accessory": "PhilipsTV",
            "name": "Philips TV",
            "ip_address": "xxx.xxx.xxx.xxx",
            "poll_status_interval": "60",
            "model_year": "2013",
            "wol_url": "wol://D0:AE:EC:57:BA:AD"
        },
        {
            "accessory": "Rituals",
            "name": "Genie",
            "account": "xxx",
            "password": "xxx"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "sudo": true,
            "platform": "config"
        },
        {
            "name": "Sonos",
            "brightness": true,
            "service": "switch",
            "speakers": false,
            "platform": "ZP"
        },
        {
            "platform": "Evohome",
            "name": "Evohome",
            "username": "xxx",
            "password": "xxx",
            "appId": "xxx",
            "switchCustom": false,
            "switchAway": false,
            "switchDayOff": false
        },
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome"
        },
        {
            "platform": "P1",
            "name": "P1",
            "timeout": 50
        },
        {
            "units": "si",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "xxx",
                    "service": "darksky",
                    "key": "xxx",
                    "locationGeo": [
                        52.027123,
                        5.1618241
                    ],
                    "language": "en",
                    "compatibility": "both",
                    "forecast": [
                        "Tomorrow"
                    ],
                    "nameForecast": "xxx",
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": true,
                    "hidden": [
                        "Air Pressure",
                        "Cloud Cover",
                        "Condition",
                        "Condition Category",
                        "Dew Point",
                        "Observation Station",
                        "Observation Time",
                        "Ozone",
                        "Rain",
                        "Rain 1h",
                        "Rain Day",
                        "Rain Chance",
                        "Snow",
                        "Solar Radiation",
                        "Sunrise Time",
                        "Sunset Time",
                        "Temperature Min",
                        "Temperature Apparent",
                        "UV Index",
                        "Visibility",
                        "Wind Direction",
                        "Wind Speed",
                        "Wind Speed Max"
                    ]
                }
            ],
            "platform": "WeatherPlus"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "groups": false,
            "group0": false,
            "heartrate": 5,
            "hosts": [
                "xxx.xxx.xxx.xxx"
            ],
            "hueMotionTemperatureHistory": true,
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "rooms": true,
            "rules": false,
            "schedules": false,
            "sensors": true,
            "timeout": 10,
            "users": {
                "xxx": "xxx"
            },
            "platform": "Hue"
        },
        {
            "refreshToken": "xxx",
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "platform": "Ring"
        },
        {
            "name": "RPi",
            "hosts": [
                {
                    "host": "localhost:8888",
                    "name": "Homebridge",
                    "noSmokeSensor": true
                }
            ],
            "platform": "RPi"
        }
    ]
}
```

**Comment by myluna08** [comment]
Another question, if you use your homebridge UI > accessories section and TAP on your genie box to START o STOP, observe your genie.

- it will answer to your actions ??
- go to rituals app, is something changed due to your actions ?

I observe in your config you not declared the HUB because I think you have only one genie in your home. Can you try to use "hub": "xxx" property in your config ??

To see what hub you have, go to your raspberry in terminal using homebridge ui for example or go with ssh.
When you start a session goto:
`homebridge@raspberrypi:~/.homebridge $ ls -la`

You will see a file like .uix-rituals-secrets_xxxxxxxx , use this xxxxx as your "hub" : "xxxx" in config, restart homebridge and try again.

**Comment by tomsteenbakkers** [comment]
> Another question, if you use your homebridge UI > accessories section and TAP on your genie box to START o STOP, observe your genie.
> 
> * it will answer to your actions ??
No, nothing happens on the Genie, light does change
> * go to rituals app, is something changed due to your actions ?
> 
No, also the app is not reflecting the change from HomeKit
> I observe in your config you not declared the HUB because I think you have only one genie in your home. Can you try to use "hub": "xxx" property in your config ??
Correct, I have only one Genie
> 
> To see what hub you have, go to your raspberry in terminal using homebridge ui for example or go with ssh.
> When you start a session goto:
> `homebridge@raspberrypi:~/.homebridge $ ls -la`
> 
> You will see a file like .uix-rituals-secrets_xxxxxxxx , use this xxxxx as your "hub" : "xxxx" in config, restart homebridge and try again.

I do no have this file. Can I get the Hub code in a different way. I can see in the Rituals app a lot item. This is also a number. Is this the hub number?

**Comment by myluna08** [comment]
You will have a file .uix-rituals-secrets_ without xxx, but missing hub property inside.
I found the error, and will be correct in the next release. Let me a few hours.

**Comment by myluna08** [comment]
Dear all @szunny @tomsteenbakkers , new 1.1.7 version is available.
This should be correct your issue. My apologies for this bug, was introduced when I will try to update this package for manage multiples genies instead of one.

**Comment by tomsteenbakkers** [comment]
> Dear all @szunny @tomsteenbakkers , new 1.1.7 version is available.
> This should be correct your issue. My apologies for this bug, was introduced when I will try to update this package for manage multiples genies instead of one.

I have installed this version but during startup I get the follow error:

```
[8/26/2020, 4:04:04 PM] ReferenceError: key is not defined
    at /usr/lib/node_modules/homebridge-rituals/index.js:167:37
    at Object.parseBody (/usr/lib/node_modules/homebridge-rituals/node_modules/request-json/main.js:74:12)
    at Request._callback (/usr/lib/node_modules/homebridge-rituals/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/lib/node_modules/homebridge-rituals/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-rituals/node_modules/request-json/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-rituals/node_modules/request-json/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
[8/26/2020, 4:04:04 PM] Got SIGTERM, shutting down Homebridge...
[8/26/2020, 4:04:04 PM] [Sonos] error: TypeError: Cannot read property 'emit' of undefined
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-zp/lib/ZpListener.js:100:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'm now back to 1.1.6 and HomeBridge is starting up again. Any ideas how to solve this?

**Comment by myluna08** [comment]
1.1.8 is the new workaround.

**Comment by tomsteenbakkers** [comment]
> 1.1.8 is the new workaround.

installed 1.1.8 and everything is working! Switching on/off in HomeKit is now show in the Rituals App and most important: the Genie is switching!

Thanks for the fast response!

**Comment by myluna08** [comment]
Great news,  ...if you like my work please!
https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=4YXRZVGSVNAEE&item_name=Just+for+a+coffe&currency_code=EUR&source=url

**Comment by tomsteenbakkers** [comment]
> Great news, ...if you like my work please!
> https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=4YXRZVGSVNAEE&item_name=Just+for+a+coffe&currency_code=EUR&source=url

Enjoy your coffee!

**Comment by tomsteenbakkers** [comment]
Just a small question. I have been testing the beta version of iPadOS.

Your plugin is working but the there is a new feature if you select a room. It's show the status of a accessory. The genie shows Not Responding.

Maybe for your next release something to look at.

![image](https://user-images.githubusercontent.com/24613800/92331526-93d1dc00-f077-11ea-86d9-99d83da43fcc.png)

**Comment by myluna08** [comment]
@tomsteenbakkers this issue has been closed, I moved your question to a new issue

**Comment by tomsteenbakkers** [comment]
@myluna08 I have installed homebridge-rituals@1.1.10 but is seems that the 'bug' is back. I can see the status in the Home app. But switching the Genie on or off in the Home App is not working.

**Comment by tomsteenbakkers** [comment]
Update: Installed version 1.1.8 and this version works. It switches the genie on and off.

**Comment by myluna08** [comment]
@tomsteenbakkers moved to new issue
