### ISSUE TITLE
Just a small question. I have been testing the beta version of iPadOS.

### ISSUE THREAD

**Issue by myluna08** [myluna08/homebridge-rituals#8]
Just a small question. I have been testing the beta version of iPadOS.

Your plugin is working but the there is a new feature if you select a room. It's show the status of a accessory. The genie shows Not Responding.

Maybe for your next release something to look at.

![image](https://user-images.githubusercontent.com/24613800/92331526-93d1dc00-f077-11ea-86d9-99d83da43fcc.png)

_Originally posted by @tomsteenbakkers in https://github.com/myluna08/homebridge-rituals/issues/7#issuecomment-687850009_

**Comment by myluna08** [comment]
Dear tom
As I can see in hap-homebridge there are more than one issue opened due to an unresponsive features.
https://github.com/homebridge/HAP-NodeJS/issues/832

**Comment by tomsteenbakkers** [comment]
Maybe it's just HomeKit which causes this. It's still in beta so we can not complain.

**Comment by myluna08** [comment]
@tomsteenbakkers maybe, but also remember that not all characteristics available in homebridge are portable to HomeKit App. For example you can add a limited number of characteristics in a single accessory.

**Comment by myluna08** [comment]
Closing issue due to wait for release. "crossing fingers"

**Comment by tomsteenbakkers** [comment]
Have figured it out what causes the 'error'. The rotation speed should always be 3% otherwise you get an error in the new Home App. The error is that the status is saying that Genie is not responding. Strange error but using the Eve app you get a better error message.

**Comment by myluna08** [comment]
Dear @tomsteenbakkers ,
We have many days with iOS14 and iOS14.0.x, Could you tell me if your Genie plugin are sometimes unresponsive ?

**Comment by tomsteenbakkers** [comment]
Yes, sometimes unresponsive and sometimes showing the wrong state. Also my Hue lamps are having these 'problems'.

**Comment by myluna08** [comment]
I still haven't found a solution, I'll keep looking

**Comment by myluna08** [comment]
@tomsteenbakkers is this issue solved in 1.1.14 ??

**Comment by tomsteenbakkers** [comment]
Yes it is!

What I also notice is that this version is must faster en reliable that the previous version.

Well done!

You can close this issue.

**Comment by myluna08** [comment]
@tomsteenbakkers Nice to hear this. Enjoy your genie. Thanks for all.
